In [2]:
import pandas as pd

data = pd.read_csv('result/survey_lgbm.csv')

data

,label,strength,model,accuracy,0_precision,0_recall,0_f1,1_precision,1_recall,1_f1,features
0,HE_obe,strong,lgbm,0.99,0.99,0.99,0.99,0.99,0.99,0.99,"['HE_ht', 'HE_wt', 'BP16_1']"
1,HE_obe,week,lgbm,0.99,0.99,1.00,0.99,1.00,0.99,0.99,"['HE_ht', 'HE_wt']"
2,HE_HCHOL,strong,lgbm,0.68,0.73,0.60,0.66,0.64,0.77,0.70,"['age', 'HE_ht', 'HE_wt', 'BE8_1']"
3,HE_HCHOL,week,lgbm,0.68,0.73,0.60,0.66,0.64,0.77,0.70,"['age', 'HE_ht', 'HE_wt', 'BE8_1']"
4,HE_HTG,strong,lgbm,0.63,0.66,0.61,0.64,0.61,0.66,0.63,"['age', 'HE_ht', 'HE_wt']"
5,HE_HTG,week,lgbm,0.63,0.66,0.61,0.64,0.61,0.66,0.63,"['age', 'HE_ht', 'HE_wt']"
6,HE_anem,strong,lgbm,0.67,0.68,0.66,0.67,0.66,0.69,0.68,"['age', 'HE_ht', 'HE_wt', 'BE8_1']"
7,HE_anem,week,lgbm,0.67,0.68,0.66,0.67,0.66,0.69,0.68,"['age', 'HE_ht', 'HE_wt', 'BE8_1']"
8,HE_HP,strong,lgbm,0.85,0.92,0.78,0.84,0.79,0.92,0.85,"['HE_wt', 'HE_ht', 'age', 'BD2', 'BE8_1', 'BE3..."
9,HE_HP,week,lgbm,0.72,0.72,0.71,0.72,0.72,0.73,0.73,"['age', 'HE_ht', 'HE_wt']"
10,HE_DM_HbA1c,strong,lgbm,0.70,0.76,0.61,0.68,0.65,0.80,0.72,"['age', 'HE_ht', 'HE_wt', 'BE8_1']"
11,HE_DM_HbA1c,week,lgbm,0.72,0.75,0.65,0.70,0.69,0.79,0.74,"['age', 'HE_ht', 'HE_wt', 'BE8_1']"